// Mocks generated by Mockito 5.4.5 from annotations
// in tarcking_app/test/widget_test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;
import 'dart:io' as _i22;

import 'package:flutter/src/widgets/navigator.dart' as _i24;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i16;
import 'package:tarcking_app/core/api/client/api_client.dart' as _i14;
import 'package:tarcking_app/features/auth/data/models/forget_password_models/forget_password_request.dart'
    as _i15;
import 'package:tarcking_app/features/auth/data/models/forget_password_models/reset_password_request_model.dart'
    as _i18;
import 'package:tarcking_app/features/auth/data/models/forget_password_models/verify_code_request_model.dart'
    as _i17;
import 'package:tarcking_app/features/auth/data/models/login/login_request.dart'
    as _i19;
import 'package:tarcking_app/features/auth/data/models/login/login_response.dart'
    as _i3;
import 'package:tarcking_app/features/auth/domain/responses/auth_response.dart'
    as _i2;
import 'package:tarcking_app/features/auth/domain/usecases/forget_password_usecase.dart'
    as _i11;
import 'package:tarcking_app/features/auth/domain/usecases/verify_code_usecase.dart'
    as _i13;
import 'package:tarcking_app/features/homescreen/data/models/orders_list_response.dart'
    as _i8;
import 'package:tarcking_app/features/myorders/data/models/my_order_list_response.dart'
    as _i9;
import 'package:tarcking_app/features/order_details/data/models/update_order_state_request_model.dart'
    as _i23;
import 'package:tarcking_app/features/order_details/data/models/update_order_state_response_model.dart'
    as _i10;
import 'package:tarcking_app/features/profile/data/models/change_password_request_model.dart'
    as _i20;
import 'package:tarcking_app/features/profile/data/models/change_password_response_model.dart'
    as _i5;
import 'package:tarcking_app/features/profile/data/models/edit_profile_request_model.dart'
    as _i21;
import 'package:tarcking_app/features/profile/data/models/edit_profile_response_model.dart'
    as _i6;
import 'package:tarcking_app/features/profile/data/models/profile_response.dart'
    as _i4;
import 'package:tarcking_app/features/profile/data/models/upload_photo_response.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthResponse_0<T> extends _i1.SmartFake
    implements _i2.AuthResponse<T> {
  _FakeAuthResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLoginResponse_1 extends _i1.SmartFake implements _i3.LoginResponse {
  _FakeLoginResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProfileResponse_2 extends _i1.SmartFake
    implements _i4.ProfileResponse {
  _FakeProfileResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChangePasswordResponseModel_3 extends _i1.SmartFake
    implements _i5.ChangePasswordResponseModel {
  _FakeChangePasswordResponseModel_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEditProfileResponseModel_4 extends _i1.SmartFake
    implements _i6.EditProfileResponseModel {
  _FakeEditProfileResponseModel_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUploadPhotoResponse_5 extends _i1.SmartFake
    implements _i7.UploadPhotoResponse {
  _FakeUploadPhotoResponse_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOrdersListResponse_6 extends _i1.SmartFake
    implements _i8.OrdersListResponse {
  _FakeOrdersListResponse_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMyOrdersListResponse_7 extends _i1.SmartFake
    implements _i9.MyOrdersListResponse {
  _FakeMyOrdersListResponse_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpdateOrderStateResponse_8 extends _i1.SmartFake
    implements _i10.UpdateOrderStateResponse {
  _FakeUpdateOrderStateResponse_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ForgetPasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockForgetPasswordUseCase extends _i1.Mock
    implements _i11.ForgetPasswordUseCase {
  MockForgetPasswordUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<_i2.AuthResponse<String>> call(String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [email],
        ),
        returnValue: _i12.Future<_i2.AuthResponse<String>>.value(
            _FakeAuthResponse_0<String>(
          this,
          Invocation.method(
            #call,
            [email],
          ),
        )),
      ) as _i12.Future<_i2.AuthResponse<String>>);
}

/// A class which mocks [VerifyCodeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockVerifyCodeUseCase extends _i1.Mock implements _i13.VerifyCodeUseCase {
  MockVerifyCodeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<_i2.AuthResponse<String>> call(String? code) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [code],
        ),
        returnValue: _i12.Future<_i2.AuthResponse<String>>.value(
            _FakeAuthResponse_0<String>(
          this,
          Invocation.method(
            #call,
            [code],
          ),
        )),
      ) as _i12.Future<_i2.AuthResponse<String>>);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i14.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<String> forgetPassword(
          _i15.ForgetPasswordRequestModel? forgetPasswordRequestModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgetPassword,
          [forgetPasswordRequestModel],
        ),
        returnValue: _i12.Future<String>.value(_i16.dummyValue<String>(
          this,
          Invocation.method(
            #forgetPassword,
            [forgetPasswordRequestModel],
          ),
        )),
      ) as _i12.Future<String>);

  @override
  _i12.Future<String> verifyResetCode(
          _i17.VerifyCodeRequestModel? verifyResetCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyResetCode,
          [verifyResetCode],
        ),
        returnValue: _i12.Future<String>.value(_i16.dummyValue<String>(
          this,
          Invocation.method(
            #verifyResetCode,
            [verifyResetCode],
          ),
        )),
      ) as _i12.Future<String>);

  @override
  _i12.Future<String> resetPassword(
          _i18.ResetPasswordRequestModel? resetPasswordRequestModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [resetPasswordRequestModel],
        ),
        returnValue: _i12.Future<String>.value(_i16.dummyValue<String>(
          this,
          Invocation.method(
            #resetPassword,
            [resetPasswordRequestModel],
          ),
        )),
      ) as _i12.Future<String>);

  @override
  _i12.Future<_i3.LoginResponse> login(_i19.LoginRequest? loginRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [loginRequest],
        ),
        returnValue: _i12.Future<_i3.LoginResponse>.value(_FakeLoginResponse_1(
          this,
          Invocation.method(
            #login,
            [loginRequest],
          ),
        )),
      ) as _i12.Future<_i3.LoginResponse>);

  @override
  _i12.Future<String> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i12.Future<String>.value(_i16.dummyValue<String>(
          this,
          Invocation.method(
            #logout,
            [],
          ),
        )),
      ) as _i12.Future<String>);

  @override
  _i12.Future<_i4.ProfileResponse> getProfile() => (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [],
        ),
        returnValue:
            _i12.Future<_i4.ProfileResponse>.value(_FakeProfileResponse_2(
          this,
          Invocation.method(
            #getProfile,
            [],
          ),
        )),
      ) as _i12.Future<_i4.ProfileResponse>);

  @override
  _i12.Future<_i5.ChangePasswordResponseModel> changePassword(
          _i20.ChangePasswordRequestModel? changePasswordRequestModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #changePassword,
          [changePasswordRequestModel],
        ),
        returnValue: _i12.Future<_i5.ChangePasswordResponseModel>.value(
            _FakeChangePasswordResponseModel_3(
          this,
          Invocation.method(
            #changePassword,
            [changePasswordRequestModel],
          ),
        )),
      ) as _i12.Future<_i5.ChangePasswordResponseModel>);

  @override
  _i12.Future<_i6.EditProfileResponseModel> editProfile(
          _i21.EditProfileRequestModel? model) =>
      (super.noSuchMethod(
        Invocation.method(
          #editProfile,
          [model],
        ),
        returnValue: _i12.Future<_i6.EditProfileResponseModel>.value(
            _FakeEditProfileResponseModel_4(
          this,
          Invocation.method(
            #editProfile,
            [model],
          ),
        )),
      ) as _i12.Future<_i6.EditProfileResponseModel>);

  @override
  _i12.Future<_i7.UploadPhotoResponse> uploadPhoto(_i22.File? photo) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadPhoto,
          [photo],
        ),
        returnValue: _i12.Future<_i7.UploadPhotoResponse>.value(
            _FakeUploadPhotoResponse_5(
          this,
          Invocation.method(
            #uploadPhoto,
            [photo],
          ),
        )),
      ) as _i12.Future<_i7.UploadPhotoResponse>);

  @override
  _i12.Future<_i8.OrdersListResponse> getOrders(
    String? bearerToken,
    int? limit, [
    int? page = 8,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrders,
          [
            bearerToken,
            limit,
            page,
          ],
        ),
        returnValue:
            _i12.Future<_i8.OrdersListResponse>.value(_FakeOrdersListResponse_6(
          this,
          Invocation.method(
            #getOrders,
            [
              bearerToken,
              limit,
              page,
            ],
          ),
        )),
      ) as _i12.Future<_i8.OrdersListResponse>);

  @override
  _i12.Future<_i9.MyOrdersListResponse> getAllOrders(String? bearerToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllOrders,
          [bearerToken],
        ),
        returnValue: _i12.Future<_i9.MyOrdersListResponse>.value(
            _FakeMyOrdersListResponse_7(
          this,
          Invocation.method(
            #getAllOrders,
            [bearerToken],
          ),
        )),
      ) as _i12.Future<_i9.MyOrdersListResponse>);

  @override
  _i12.Future<_i10.UpdateOrderStateResponse> updateOrderState(
    String? orderId,
    _i23.UpdateOrderStateRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOrderState,
          [
            orderId,
            request,
          ],
        ),
        returnValue: _i12.Future<_i10.UpdateOrderStateResponse>.value(
            _FakeUpdateOrderStateResponse_8(
          this,
          Invocation.method(
            #updateOrderState,
            [
              orderId,
              request,
            ],
          ),
        )),
      ) as _i12.Future<_i10.UpdateOrderStateResponse>);
}

/// A class which mocks [NavigatorObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigatorObserver extends _i1.Mock implements _i24.NavigatorObserver {
  MockNavigatorObserver() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void didPush(
    _i24.Route<dynamic>? route,
    _i24.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didPush,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didPop(
    _i24.Route<dynamic>? route,
    _i24.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didPop,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didRemove(
    _i24.Route<dynamic>? route,
    _i24.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didRemove,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didReplace({
    _i24.Route<dynamic>? newRoute,
    _i24.Route<dynamic>? oldRoute,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #didReplace,
          [],
          {
            #newRoute: newRoute,
            #oldRoute: oldRoute,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeTop(
    _i24.Route<dynamic>? topRoute,
    _i24.Route<dynamic>? previousTopRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didChangeTop,
          [
            topRoute,
            previousTopRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didStartUserGesture(
    _i24.Route<dynamic>? route,
    _i24.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didStartUserGesture,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didStopUserGesture() => super.noSuchMethod(
        Invocation.method(
          #didStopUserGesture,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
