// Mocks generated by Mockito 5.4.4 from annotations
// in tarcking_app/test/features/profile/presentation/view/widgets/profile_components_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_bloc/flutter_bloc.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tarcking_app/features/profile/domain/entity/user_entity.dart'
    as _i4;
import 'package:tarcking_app/features/profile/presentation/viewmodel/profile_viewmodel.dart'
    as _i3;
import 'package:tarcking_app/features/profile/presentation/viewmodel/states/profile_states.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProfileStates_0 extends _i1.SmartFake implements _i2.ProfileStates {
  _FakeProfileStates_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProfileViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileViewModel extends _i1.Mock implements _i3.ProfileViewModel {
  MockProfileViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set user(_i4.UserEntity? _user) => super.noSuchMethod(
    Invocation.setter(#user, _user),
    returnValueForMissingStub: null,
  );

  @override
  _i2.ProfileStates get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeProfileStates_0(this, Invocation.getter(#state)),
          )
          as _i2.ProfileStates);

  @override
  _i5.Stream<_i2.ProfileStates> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i5.Stream<_i2.ProfileStates>.empty(),
          )
          as _i5.Stream<_i2.ProfileStates>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i5.Future<void> getProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void clearProfileCache() => super.noSuchMethod(
    Invocation.method(#clearProfileCache, []),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i2.ProfileStates? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i6.Change<_i2.ProfileStates>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
