// Mocks generated by Mockito 5.4.5 from annotations
// in tarcking_app/test/features/auth/data/repositories_implementation/auth_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dio/dio.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i13;
import 'package:tarcking_app/features/auth/data/datasource/auth_remote_data_source.dart'
    as _i5;
import 'package:tarcking_app/features/auth/data/models/apply_models/driver.dart'
    as _i2;
import 'package:tarcking_app/features/auth/data/models/apply_models/vehicles_response.dart'
    as _i3;
import 'package:tarcking_app/features/auth/data/models/forget_password_models/forget_password_request.dart'
    as _i10;
import 'package:tarcking_app/features/auth/data/models/forget_password_models/reset_password_request_model.dart'
    as _i12;
import 'package:tarcking_app/features/auth/data/models/forget_password_models/verify_code_request_model.dart'
    as _i11;
import 'package:tarcking_app/features/auth/data/models/login/login_request.dart'
    as _i9;
import 'package:tarcking_app/features/auth/data/models/login/login_response.dart'
    as _i8;
import 'package:tarcking_app/features/auth/domain/responses/auth_response.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDriver_0 extends _i1.SmartFake implements _i2.Driver {
  _FakeDriver_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVehiclesResponse_1 extends _i1.SmartFake
    implements _i3.VehiclesResponse {
  _FakeVehiclesResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthResponse_2<T> extends _i1.SmartFake
    implements _i4.AuthResponse<T> {
  _FakeAuthResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDatasource extends _i1.Mock
    implements _i5.AuthRemoteDatasource {
  MockAuthRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Driver> applyDriver({
    required String? country,
    required String? firstName,
    required String? lastName,
    required String? vehicleType,
    required String? vehicleNumber,
    required _i7.MultipartFile? vehicleLicense,
    required String? nid,
    required _i7.MultipartFile? nidImg,
    required String? email,
    required String? password,
    required String? rePassword,
    required String? gender,
    required String? phone,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #applyDriver,
          [],
          {
            #country: country,
            #firstName: firstName,
            #lastName: lastName,
            #vehicleType: vehicleType,
            #vehicleNumber: vehicleNumber,
            #vehicleLicense: vehicleLicense,
            #nid: nid,
            #nidImg: nidImg,
            #email: email,
            #password: password,
            #rePassword: rePassword,
            #gender: gender,
            #phone: phone,
          },
        ),
        returnValue: _i6.Future<_i2.Driver>.value(_FakeDriver_0(
          this,
          Invocation.method(
            #applyDriver,
            [],
            {
              #country: country,
              #firstName: firstName,
              #lastName: lastName,
              #vehicleType: vehicleType,
              #vehicleNumber: vehicleNumber,
              #vehicleLicense: vehicleLicense,
              #nid: nid,
              #nidImg: nidImg,
              #email: email,
              #password: password,
              #rePassword: rePassword,
              #gender: gender,
              #phone: phone,
            },
          ),
        )),
      ) as _i6.Future<_i2.Driver>);

  @override
  _i6.Future<_i3.VehiclesResponse> getVehicles() => (super.noSuchMethod(
        Invocation.method(
          #getVehicles,
          [],
        ),
        returnValue:
            _i6.Future<_i3.VehiclesResponse>.value(_FakeVehiclesResponse_1(
          this,
          Invocation.method(
            #getVehicles,
            [],
          ),
        )),
      ) as _i6.Future<_i3.VehiclesResponse>);

  @override
  _i6.Future<_i4.AuthResponse<_i8.LoginResponse>> login(
          _i9.LoginRequest? loginRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [loginRequest],
        ),
        returnValue: _i6.Future<_i4.AuthResponse<_i8.LoginResponse>>.value(
            _FakeAuthResponse_2<_i8.LoginResponse>(
          this,
          Invocation.method(
            #login,
            [loginRequest],
          ),
        )),
      ) as _i6.Future<_i4.AuthResponse<_i8.LoginResponse>>);

  @override
  _i6.Future<_i4.AuthResponse<String>> forgetPassword(
          _i10.ForgetPasswordRequestModel? forgetPasswordRequestModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgetPassword,
          [forgetPasswordRequestModel],
        ),
        returnValue: _i6.Future<_i4.AuthResponse<String>>.value(
            _FakeAuthResponse_2<String>(
          this,
          Invocation.method(
            #forgetPassword,
            [forgetPasswordRequestModel],
          ),
        )),
      ) as _i6.Future<_i4.AuthResponse<String>>);

  @override
  _i6.Future<_i4.AuthResponse<String>> verifyResetPassword(
          _i11.VerifyCodeRequestModel? verifyCodeRequestModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyResetPassword,
          [verifyCodeRequestModel],
        ),
        returnValue: _i6.Future<_i4.AuthResponse<String>>.value(
            _FakeAuthResponse_2<String>(
          this,
          Invocation.method(
            #verifyResetPassword,
            [verifyCodeRequestModel],
          ),
        )),
      ) as _i6.Future<_i4.AuthResponse<String>>);

  @override
  _i6.Future<_i4.AuthResponse<String>> resetPassword(
          _i12.ResetPasswordRequestModel? resetPasswordRequestModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [resetPasswordRequestModel],
        ),
        returnValue: _i6.Future<_i4.AuthResponse<String>>.value(
            _FakeAuthResponse_2<String>(
          this,
          Invocation.method(
            #resetPassword,
            [resetPasswordRequestModel],
          ),
        )),
      ) as _i6.Future<_i4.AuthResponse<String>>);

  @override
  _i6.Future<String> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i6.Future<String>.value(_i13.dummyValue<String>(
          this,
          Invocation.method(
            #logout,
            [],
          ),
        )),
      ) as _i6.Future<String>);
}
