// Mocks generated by Mockito 5.4.5 from annotations
// in tarcking_app/test/features/profile/api/datasource_impl/profile_remote_datasource_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;
import 'dart:io' as _i19;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i13;
import 'package:tarcking_app/core/api/client/api_client.dart' as _i10;
import 'package:tarcking_app/features/auth/data/models/forget_password_models/forget_password_request.dart'
    as _i12;
import 'package:tarcking_app/features/auth/data/models/forget_password_models/reset_password_request_model.dart'
    as _i15;
import 'package:tarcking_app/features/auth/data/models/forget_password_models/verify_code_request_model.dart'
    as _i14;
import 'package:tarcking_app/features/auth/data/models/login/login_request.dart'
    as _i16;
import 'package:tarcking_app/features/auth/data/models/login/login_response.dart'
    as _i2;
import 'package:tarcking_app/features/homescreen/data/models/orders_list_response.dart'
    as _i7;
import 'package:tarcking_app/features/myorders/data/models/my_order_list_response.dart'
    as _i8;
import 'package:tarcking_app/features/order_details/data/models/update_order_state_request_model.dart'
    as _i20;
import 'package:tarcking_app/features/order_details/data/models/update_order_state_response_model.dart'
    as _i9;
import 'package:tarcking_app/features/profile/data/models/change_password_request_model.dart'
    as _i17;
import 'package:tarcking_app/features/profile/data/models/change_password_response_model.dart'
    as _i4;
import 'package:tarcking_app/features/profile/data/models/edit_profile_request_model.dart'
    as _i18;
import 'package:tarcking_app/features/profile/data/models/edit_profile_response_model.dart'
    as _i5;
import 'package:tarcking_app/features/profile/data/models/profile_response.dart'
    as _i3;
import 'package:tarcking_app/features/profile/data/models/upload_photo_response.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLoginResponse_0 extends _i1.SmartFake implements _i2.LoginResponse {
  _FakeLoginResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProfileResponse_1 extends _i1.SmartFake
    implements _i3.ProfileResponse {
  _FakeProfileResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChangePasswordResponseModel_2 extends _i1.SmartFake
    implements _i4.ChangePasswordResponseModel {
  _FakeChangePasswordResponseModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEditProfileResponseModel_3 extends _i1.SmartFake
    implements _i5.EditProfileResponseModel {
  _FakeEditProfileResponseModel_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUploadPhotoResponse_4 extends _i1.SmartFake
    implements _i6.UploadPhotoResponse {
  _FakeUploadPhotoResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOrdersListResponse_5 extends _i1.SmartFake
    implements _i7.OrdersListResponse {
  _FakeOrdersListResponse_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMyOrdersListResponse_6 extends _i1.SmartFake
    implements _i8.MyOrdersListResponse {
  _FakeMyOrdersListResponse_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpdateOrderStateResponse_7 extends _i1.SmartFake
    implements _i9.UpdateOrderStateResponse {
  _FakeUpdateOrderStateResponse_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i10.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<String> forgetPassword(
          _i12.ForgetPasswordRequestModel? forgetPasswordRequestModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgetPassword,
          [forgetPasswordRequestModel],
        ),
        returnValue: _i11.Future<String>.value(_i13.dummyValue<String>(
          this,
          Invocation.method(
            #forgetPassword,
            [forgetPasswordRequestModel],
          ),
        )),
      ) as _i11.Future<String>);

  @override
  _i11.Future<String> verifyResetCode(
          _i14.VerifyCodeRequestModel? verifyResetCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyResetCode,
          [verifyResetCode],
        ),
        returnValue: _i11.Future<String>.value(_i13.dummyValue<String>(
          this,
          Invocation.method(
            #verifyResetCode,
            [verifyResetCode],
          ),
        )),
      ) as _i11.Future<String>);

  @override
  _i11.Future<String> resetPassword(
          _i15.ResetPasswordRequestModel? resetPasswordRequestModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [resetPasswordRequestModel],
        ),
        returnValue: _i11.Future<String>.value(_i13.dummyValue<String>(
          this,
          Invocation.method(
            #resetPassword,
            [resetPasswordRequestModel],
          ),
        )),
      ) as _i11.Future<String>);

  @override
  _i11.Future<_i2.LoginResponse> login(_i16.LoginRequest? loginRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [loginRequest],
        ),
        returnValue: _i11.Future<_i2.LoginResponse>.value(_FakeLoginResponse_0(
          this,
          Invocation.method(
            #login,
            [loginRequest],
          ),
        )),
      ) as _i11.Future<_i2.LoginResponse>);

  @override
  _i11.Future<String> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i11.Future<String>.value(_i13.dummyValue<String>(
          this,
          Invocation.method(
            #logout,
            [],
          ),
        )),
      ) as _i11.Future<String>);

  @override
  _i11.Future<_i3.ProfileResponse> getProfile() => (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [],
        ),
        returnValue:
            _i11.Future<_i3.ProfileResponse>.value(_FakeProfileResponse_1(
          this,
          Invocation.method(
            #getProfile,
            [],
          ),
        )),
      ) as _i11.Future<_i3.ProfileResponse>);

  @override
  _i11.Future<_i4.ChangePasswordResponseModel> changePassword(
          _i17.ChangePasswordRequestModel? changePasswordRequestModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #changePassword,
          [changePasswordRequestModel],
        ),
        returnValue: _i11.Future<_i4.ChangePasswordResponseModel>.value(
            _FakeChangePasswordResponseModel_2(
          this,
          Invocation.method(
            #changePassword,
            [changePasswordRequestModel],
          ),
        )),
      ) as _i11.Future<_i4.ChangePasswordResponseModel>);

  @override
  _i11.Future<_i5.EditProfileResponseModel> editProfile(
          _i18.EditProfileRequestModel? model) =>
      (super.noSuchMethod(
        Invocation.method(
          #editProfile,
          [model],
        ),
        returnValue: _i11.Future<_i5.EditProfileResponseModel>.value(
            _FakeEditProfileResponseModel_3(
          this,
          Invocation.method(
            #editProfile,
            [model],
          ),
        )),
      ) as _i11.Future<_i5.EditProfileResponseModel>);

  @override
  _i11.Future<_i6.UploadPhotoResponse> uploadPhoto(_i19.File? photo) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadPhoto,
          [photo],
        ),
        returnValue: _i11.Future<_i6.UploadPhotoResponse>.value(
            _FakeUploadPhotoResponse_4(
          this,
          Invocation.method(
            #uploadPhoto,
            [photo],
          ),
        )),
      ) as _i11.Future<_i6.UploadPhotoResponse>);

  @override
  _i11.Future<_i7.OrdersListResponse> getOrders(
    String? bearerToken,
    int? limit, [
    int? page = 8,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrders,
          [
            bearerToken,
            limit,
            page,
          ],
        ),
        returnValue:
            _i11.Future<_i7.OrdersListResponse>.value(_FakeOrdersListResponse_5(
          this,
          Invocation.method(
            #getOrders,
            [
              bearerToken,
              limit,
              page,
            ],
          ),
        )),
      ) as _i11.Future<_i7.OrdersListResponse>);

  @override
  _i11.Future<_i8.MyOrdersListResponse> getAllOrders(String? bearerToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllOrders,
          [bearerToken],
        ),
        returnValue: _i11.Future<_i8.MyOrdersListResponse>.value(
            _FakeMyOrdersListResponse_6(
          this,
          Invocation.method(
            #getAllOrders,
            [bearerToken],
          ),
        )),
      ) as _i11.Future<_i8.MyOrdersListResponse>);

  @override
  _i11.Future<_i9.UpdateOrderStateResponse> updateOrderState(
    String? orderId,
    _i20.UpdateOrderStateRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOrderState,
          [
            orderId,
            request,
          ],
        ),
        returnValue: _i11.Future<_i9.UpdateOrderStateResponse>.value(
            _FakeUpdateOrderStateResponse_7(
          this,
          Invocation.method(
            #updateOrderState,
            [
              orderId,
              request,
            ],
          ),
        )),
      ) as _i11.Future<_i9.UpdateOrderStateResponse>);
}
